##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: "/project1/collectionbuilder-gh"
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: COLONIAL LAND ACQUISITION AND INDIGENOUS RESISTANCE IN ENUGU NIGERIA, 1915-1950-GH 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Exploring power, land, and indigenous resilence in the face of colonial expansion.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This Project examines the interactions between colonial authorities and indigenous communities in Enugu Nigeria during the 20th century drive to acquire land for government extractive projects. Focusing on compensation demands, legal disputes, and the enduring resistance of local chiefs, this study reveals the complexities of land ownership, indigenous resistance, cultural preservation, and administrative negotiation within the colonial framework."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Uzoamaka Nwachukwu

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: metadata-template

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "History Department, Indiana University"
# organization-link: https://history.indiana.edu/graduate/index.html
# organization-logo-banner: https://www.iu.edu/brand/design/logo-and-marks/index.html
# organization-logo-nav: https://www.iu.edu/brand/design/logo-and-marks/index.html

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
